tasks:
  - name: install dependencies
    init: npm install --prefix servidor
    command: npm start --prefix servidor
  - name: generate private key
    command: sh generate-private-key.sh

ports:
  - port: 3000
    onOpen: open-browser